### PR TITLE
Standby mode metric

### PR DESCRIPTION
**Pull request by rmontenegroo**
Hi!

I just added the host standbyMode metric. Not a big change at all.

https://code.vmware.com/apis/196/vsphere/doc/vim.HostSystem.StandbyMode.html

### CODE REVIEW

**Comment by pryorda** [comment]
@rmontenegroo Hello and Thank you for the PR! This all looks good but is there any way we could get a test for it this metric?

**Comment by rmontenegroo** [comment]
Sure! Trying to follow your CI script test. Using python 3.6.9 here but I got 
```
(python3.6) rodmonte@deadpool:~/develop/vmware_exporter$ pytest --cov=. -v tests/unit
Traceback (most recent call last):
  File "/home/rodmonte/develop/python3.6/bin/pytest", line 5, in <module>
    from pytest import main
  File "/home/rodmonte/develop/python3.6/lib/python3.6/site-packages/pytest.py", line 13, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/home/rodmonte/develop/python3.6/lib/python3.6/site-packages/_pytest/fixtures.py", line 839, in <module>
    class FixtureFunctionMarker(object):
  File "/home/rodmonte/develop/python3.6/lib/python3.6/site-packages/_pytest/fixtures.py", line 841, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))
TypeError: attrib() got an unexpected keyword argument 'convert'
```
right after pip installing requirements.
Any tip?

**Comment by Jc2k** [comment]
Does this help? https://github.com/pytest-dev/pytest/issues/5903

**Comment by rmontenegroo** [comment]
@Jc2k Thanks for the tip!
I changed requirements-test.txt so as to get tests working here:
```
pytest_docker_tools==0.2.0
pytest==5.4.1
pytest-cov==2.8.1
pytest-twisted==1.12
codecov==2.0.15
flake8==3.6.0
```

**Pull request closed without merging**
