### PR TITLE
Fix #40, move threader shutdown after all work has completed

### LINKED ISSUE #40: Metrics for only one host or datastore instance are reported
Helllo,

VMware exporter returns metrics only for one host or datastore instance.

Environment:
vmware_exporter.py v0.3.0
Python 3.5.2 (Ubuntu) & Python 3.6.6 (OpenBSD)
I've checked that all permissions are correct on vSphere side and also tried connecting by using administrator account.

Steps to reproduce:
```
$ cat config.yml
default:
    vsphere_host: "hostname"   # this is vCenter host
    vsphere_user: 'username'
    vsphere_password: 'password'
    ignore_ssl: True
    collect_only:
        vms: False
        vmguests: False
        datastores: True
        hosts: True
        snapshots: False
$ ./vmware_exporter.py -c config.yml
$ curl -s localhost:9272/metrics | grep -v "#"
vmware_host_power_state{cluster_name="XXX cluster",dc_name="DC_NAME",host_name="vm1.example.com"} 1.0
```

Applying following patch shows that only first host or datastore is processed in for loop:
```
--- vmware_exporter.py.orig     2018-12-20 14:11:48.535447407 +0100
+++ vmware_exporter.py  2018-12-20 14:15:59.207702036 +0100
@@ -299,7 +299,9 @@
         """
         log("Starting datastore metrics collection")
         datastores = self._vmware_get_obj(content, [vim.Datastore])
+        print(datastores)
         for datastore in datastores:
+            print(datastore)
             # ds.RefreshDatastoreStorageInfo()
             summary = datastore.summary
             ds_name = summary.name
@@ -461,7 +463,9 @@
         """
         log("Starting host metrics collection")
         hosts = self._vmware_get_obj(content, [vim.HostSystem])
+        print(hosts)
         for host in hosts:
+            print(host)
             summary = host.summary
             host_name, host_dc_name, host_cluster_name = self._vmware_host_metadata(inventory, host)
             host_metadata = [host_name, host_dc_name, host_cluster_name]
```
Output after applying patch:
```
$ ./vmware_exporter.py -c config.yml 
[2018-12-20 13:21:36.743208+00:00] Starting web server on port 9272
[2018-12-20 13:21:41.860451+00:00] Start collecting metrics from hostname
[2018-12-20 13:21:42.041749+00:00] Starting inventory collection
[2018-12-20 13:21:43.712368+00:00] Finished inventory collection
[2018-12-20 13:21:43.712878+00:00] Starting datastore metrics collection
[2018-12-20 13:21:43.713506+00:00] Starting host metrics collection
(ManagedObject) [
   'vim.Datastore:datastore-1263',
   'vim.Datastore:datastore-26',
   'vim.Datastore:datastore-29',
   'vim.Datastore:datastore-25',
   'vim.Datastore:datastore-28',
   'vim.Datastore:datastore-6324',
   'vim.Datastore:datastore-1261',
   'vim.Datastore:datastore-369',
   'vim.Datastore:datastore-3412',
   'vim.Datastore:datastore-6169',
   'vim.Datastore:datastore-6167',
   'vim.Datastore:datastore-2064',
   'vim.Datastore:datastore-2065',
   'vim.Datastore:datastore-12841',
   'vim.Datastore:datastore-12847',
   'vim.Datastore:datastore-27354',
   'vim.Datastore:datastore-27349'
]
'vim.Datastore:datastore-1263'
(ManagedObject) [
   'vim.HostSystem:host-1487',
   'vim.HostSystem:host-1315',
   'vim.HostSystem:host-1390',
   'vim.HostSystem:host-1260',
   'vim.HostSystem:host-1460',
   'vim.HostSystem:host-1462',
   'vim.HostSystem:host-24',
   'vim.HostSystem:host-27',
   'vim.HostSystem:host-6322',
   'vim.HostSystem:host-3411',
   'vim.HostSystem:host-367',
   'vim.HostSystem:host-6246',
   'vim.HostSystem:host-6276',
   'vim.HostSystem:host-6255',
   'vim.HostSystem:host-6194',
   'vim.HostSystem:host-6166',
   'vim.HostSystem:host-6205',
   'vim.HostSystem:host-2063',
   'vim.HostSystem:host-12840',
   'vim.HostSystem:host-12846',
   'vim.HostSystem:host-27348',
   'vim.HostSystem:host-27353'
]
'vim.HostSystem:host-1487'
[2018-12-20 13:21:43.828089+00:00] Finished collecting metrics from hostname
```

### PR DESCRIPTION
**Pull request by dannyk81**
@pryorda @jc2k this fixes #40 for me

please take a look

### CODE REVIEW

**Comment by Jc2k** [comment]
The threader shutdown is where it was because there is a dependency between the vm metrics and the vm perf counters (it assumes self._labels is populated already). So this is probably introducing a non deterministic race 😞

**Comment by dannyk81** [comment]
Ohhh... I see it now.

Well, looks like using the threader after it was already shutdown is causing some issues.

Perhaps the dependency can be more explicitly defined? maybe using separate execute contexts?

**Comment by Jc2k** [comment]
Ahh! Because you can’t submit jobs after shutdown is called! Of course!

Well I can probably get rid of the nested threads all together with a property collector (it can fetch all data for all hosts and data stores in one call). Will try and look at doing that.

**Comment by dannyk81** [comment]
That'd be great @Jc2k, I'm going to close this PR on account that this fix is not safe.

@pryorda FYI though that v0.3.0 is currently broken for hosts and datastores, but with @Jc2k's help we should be able to fix this.

**Comment by pryorda** [comment]
@Jc2k @dannyk81 Good finds. I'm surprised we didn't noticed this in the PR. I think pushing the shutdown lower down should be fine. @Jc2k Can you elaborate on the Race Condition you're worried about?

**Comment by pryorda** [comment]
@dannyk81 I don't want to close this just yet.  This might be the immediate fix, but not the log term solution.

**Comment by Jc2k** [comment]
I think that this PR is unsafe, and is trading one race for another. After this PR is merged the extra code that runs early depends on self._labels. That structure is generated on a thread. The current way ensures that structure is populated before the code that uses it runs. The new way allows it to run before it exists.

**Comment by dannyk81** [comment]
@pryorda I didn't see the issue that pushing down the shutdown was creating, but this fix as-is creates another problem.

I suggest to close this and work on a fix which will reconcile both races properly.

**Comment by pryorda** [comment]
We should able to force a thread completion before moving on. I think you're right in saying that maybe we should remove some of the nested threading

**Comment by pryorda** [comment]
Do we want to continue the conversation here or move it to #41 and #40?

**Comment by dannyk81** [comment]
I suggest we close this one and discuss this over in #40

**Pull request closed without merging**
