### PR TITLE
Fix UTF-8 encoding

### LINKED ISSUE #24: UTF8 Error
Hi,
We have a VM called 'Serveur Modèle'.
During scraping, the following error occurs:
[2018-09-19 08:48:17.842438+00:00] Start collecting vcenter metrics for vcenter
[2018-09-19 08:48:18.163349+00:00] Starting VM performance metric collection
[2018-09-19 08:48:18.172564+00:00] Total Virtual Machines: 79
[2018-09-19 08:48:24.360088+00:00] Finish starting vm performance vm collection
[2018-09-19 08:48:24.360130+00:00] Starting VM snapshot metric collection
[2018-09-19 08:48:25.045333+00:00] Finished VM snapshot metric collection
[2018-09-19 08:48:25.045381+00:00] Stop collecting vcenter metrics for vcenter
[2018-09-19 08:48:25.053014+00:00] [Failure instance: Traceback: <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode character u'\xe8' in position 11: ordinal not in range(128)
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1208:mainLoop
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:828:runUntilCurrent
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:457:callback
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:565:_startRunCallbacks
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:651:_runCallbacks
/usr/local/bin/vmware_exporter.py:129:generate_latest_metrics
]
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1208, in mainLoop
    self.runUntilCurrent()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 828, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 457, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 565, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/bin/vmware_exporter.py", line 129, in generate_latest_metrics
    for k, v in sorted(labels.items())]))
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 11: ordinal not in range(128)

To fix this issue, I did the following modifications in vmware_exporter.py:
line 128:   k, v.replace('\\', r'\\').replace('\n', r'\n').replace('"', r'\"').encode('utf-8'))
line 139:   request.write(''.join(output))

I don't know if it's the cleanest way to fix the problem, but it works.

### PR DESCRIPTION
**Pull request by jnogol**
Fixes #24 

Based on @bmeneuvrier proposal.

@pryorda, a couple things:
- Would you add a changelog in the near future?
- Thanks for the exporter, and for maintaining it ;)

### CODE REVIEW

**Comment by pryorda** [comment]
I'm comfortable with this change. What about you @dannyk81

**Comment by pryorda** [comment]
Also, we should start a changlog. Do you mind adding it to your PR?

**Comment by jnogol** [comment]
Done, but since I don't know the changes from previous releases, I only added the "unreleased" part

**Comment by pryorda** [comment]
To be fair, I took this over from another dev. I do not know all the versions. It will be more of a going forward change log.

**Comment by dannyk81** [comment]
Sorry for the delay there, this lgtm! and adding a changelog is a good idea.

**Comment by pryorda** [comment]
I broke this PR and working on new one.

**Pull request closed without merging**
