### PR TITLE
add template metric to know if vm is a template or not

### PR DESCRIPTION
**Pull request by alecorps**
Hello,

I added this metric to be able to know if a vm is a template or not and to be able in grafana to evict template in dashboards

### CODE REVIEW

**Comment by dannyk81** [comment]
@alecorps that's indeed a useful metric to have! could you add tests please?

**Comment by alecorps** [comment]
I just added the tests

**Comment by dannyk81** [comment]
@alecorps looks like you've added code from your PRs to this branch, I suggest we keep each PR focused on a specific change so it can be evaluated and merged separately.

**Comment by alecorps** [comment]
I will emit a new PR per feature

**Pull request closed without merging**
