### PR TITLE
added a landing page, with a link to metrics. to make it more in line…

### PR DESCRIPTION
**Pull request by cybervedaa**
added a landing page, with a link to metrics. to make it more in line like other prometheus exporters

As discussed here https://github.com/pryorda/vmware_exporter/pull/99#issuecomment-486926212

### CODE REVIEW

**Comment by pryorda** [comment]
Could you add a test for this please?

**Comment by cybervedaa** [comment]
@pryorda - as requested, i have added a test case. please check and let me know if it looks ok.

**Comment by kremers** [comment]
@cybervedaa can you rebase the change?

**Comment by kremers** [comment]
Updated the PR in #108

**Pull request closed without merging**
