### PR TITLE
Add maxlimited metric

### PR DESCRIPTION
**Pull request by blemmenes**
Needed to add this in order to be able to highlight VMs that are experiencing CPU Ready that wasn't due to Resource Pool limitations. Ie vmware_vm_cpu_ready - vmware_vm_cpu_maxlimited.

Useful for managing capacity/over commitment ratios.

Thanks,
Berant

### CODE REVIEW

**Comment by pryorda** [comment]
Can you link me to the docs around this?

**Comment by pryorda** [comment]
Also, could you update the tests for this case?

**Comment by pryorda** [comment]
Nvm on linking: https://www.vmware.com/support/developer/converter-sdk/conv61_apireference/cpu_counters.html

**Comment by blemmenes** [comment]
@pryorda No problem, happy too. You are correct on API reference doc. 

I'd be happy to fix the unit tests. I've not done much with unit tests, is it as simple as adding the maxlimited metric to the dictionary in both test_no_error_onempty_vms and test_collect_vm_perf?

**Comment by blemmenes** [comment]
@pryorda  I *think* that I adjusted the unit test appropriately. It's passing at least, though clearly that doesn't preclude me doing it in a nonsensical way. ;)

**Pull request merged**
