### PR TITLE
fix(idle_connections): Fixing idle connections and formatting

### LINKED ISSUE #109: Multiple idling sessions from exporter in VC
Hi,
I use exporter to collect metrics from Vcenter. 
On Vcenter monitor/sessions I noticed many(~30) idling sessions from exporter. Any reason why the sessions are not closed by exporter?

### PR DESCRIPTION
**Pull request by pryorda**
This fixes #109 and adds some formatting.

Precommit-Verified: 1d89f3b71592aabf931814b50d0088977367f936c12a6819f45e9b1b8d6ec2c5

### CODE REVIEW

**Comment by pryorda** [comment]
With the severity of this bug, I'm going to merge and get it out. It's causing some resource issues on our vcenter instance.

**Comment by kremers** [comment]
> With the severity of this bug, I'm going to merge and get it out. It's causing some resource issues on our vcenter instance.

Fixes test

```
@@ -482,7 +482,7 @@ def test_collect():
         ).return_value = _succeed(True)
         stack.enter_context(mock.patch.object(collector, '_vmware_get_datastores')).return_value = _succeed(True)
         stack.enter_context(mock.patch.object(collector, '_vmware_get_hosts')).return_value = _succeed(True)
-        stack.enter_context(mock.patch.object(collector, '_vmware_disconnect')).return_value = _succeed(None)
+        stack.enter_context(mock.patch.object(collector, '_vmware_disconnect')).return_value = _succeed(True)
         metrics = yield collector.collect()
```

**Comment by pryorda** [comment]
Looks like I need to to fix the tests so they don't freeze up. Not sure where to start

**Comment by Jc2k** [comment]
@pryorda The diff from @kremers fixes it for me

**Comment by kremers** [comment]
PR #108 has been updated, fixing all open PRs/Issues

Just saying

**Comment by pryorda** [comment]
closing in favor of 108

**Pull request closed without merging**
