### PR TITLE
Port to Python3 + 6x speed up

### PR DESCRIPTION
**Pull request by Jc2k**
Hi

I started porting to Python 3 as I am trying to not deploy new Python 2 code. In doing so I was hitting 1 minute fetches against my ESXi boxes largely due to the number of VM's. So i've started doing some performance work as well. Sorry it has ended up in a big PR (although its a net reduction).

This is now running on Python 3.6/7 for me.

The headline performance changes are:

 * I only call `content.perfManager.QueryStats` once. Previously it was called `len(perf_list) * len(virtual_machines) times`, which was a big number for me. Lots of HTTP round tripping.
 * I then tried to reduce the amount of times I needed to access vm parameters in different threads as I was actually causing the same SOAP calls multiple times, again multiplied by the number of vms. So accessing the the `name` field of an `entity` returned by `QueryStats` was painful. 
 * Having multiple threads iterate over all vms and do a vm.summary was also painful. So I conslidated 3 sets of stats that relied on this.
 * I run the host and datastore scrapes in parallel now.

Before these changes it takes 1m5s on my test environment. This is a single node ESXi box with hundreds of vms and no snapshots. Afterwards it takes 8-11s.

This fixes a bunch of threading bugs.

 * The threadit code. It does a join in the handler for `/metrics` but it will only join() the most recent thread. Thats racy. If there are 10 threads and it only waits for the most recent thread to finish it might miss data from 9 of those older threads if they run for longer than the newest thread.

 * Blocking when calling `thread_it`. If there are 10 threads the old code would block until the newest thread was complete. This is bad performance wise. The 9 older threads can finish and then you stall - there are 9 threads of capacity that are idle because the newest thread is still running. It's also blocking the reactor while the 10th thread finishes.

I've fixed both of these by switching to a ThreadPoolExecutor. Submitting doesn't block. When stopping the threadpool you can wait for all tasks to complete.

I suspect there was a third bug in snapshot handling too. `_vmware_get_snapshots` creates a list and starts N threads. It then returns that list to its caller. The caller then immediately loops over those lists and emits metrics. There is no synchronization here. There is no guarantee that the threads will have finished by the time the lists are read. I've actually merged this into the existing vm threads - this ends up being more efficient as it doesnt need to fetch the same `vim.VirtualMachine `object multiple times for each VM.

I also refactored the code into web code and a prometheur Collector object that can be passed into the prometheus_client's code to generate the metrics output. The code in vmware_exporter is orginally from prometheus_client so it seems better to use the upstream serializing code rather than a copy and paste.

The net result is that overall i've deleted 100 lines, made it 6x faster and prepared us for the python 2 free future that is just round the corner!

There is still more work todo, but if this is going upstream it will have to wait for PR 2. (In particular, this is running quite a lot of blocking code on the event loop thread. I want to try and make use of twisteds threading code here).

### CODE REVIEW

**Comment by pryorda** [comment]
This is great. I'll review asap and let you know if I have anything to add.

**Comment by pryorda** [comment]
@Jc2k this was not actually reverted. It does look like I'll have to do some work around snapshots.

**Comment by Jc2k** [comment]
@pryorda I just pushed 5381974465a4ed66c6b9cc10b87648e44bda6697 which should hopefully fix snapshots (it did for me).

**Comment by pryorda** [comment]
Ha I was just looking to do that in the for loop later. It would be nice if it raised the type error instead silently dropping it. What lead you to this? I'll likely merge your change instead of mine.

**Comment by Jc2k** [comment]
Yeah I think threadpool.submit() returns a future that you have to call result() or something on to see the errors. I’ll see if I can make it do anything nicer.

Tbh I knew what I expected to happen and just peppered it with loads of print statements 😂

**Comment by pryorda** [comment]
I really need to stop all changes to this till we get all the unit tests in.

**Pull request merged**
