### PR TITLE
add collect host perf counter and tests

### PR DESCRIPTION
**Pull request by alecorps**
Add host perf counters collector to have the perf counter of esxi and be able to create some usage and troubleshooting ESXi dashboards and alerts in grafana and alert manager.
Added some unit tests
Some other counters can be added, i put usefull one

### CODE REVIEW

**Comment by dannyk81** [comment]
LGTM as well, this adds quite a bit of metrics but considering it's scoped to hosts that shouldn't have any significant impact on cardinality and scrape times.

**Comment by pryorda** [comment]
> LGTM as well, this adds quite a bit of metrics but considering it's scoped to hosts that shouldn't have any significant impact on cardinality and scrape times.

I was thinking that too was going to do a feat rather then fix.

**Comment by alecorps** [comment]
Thanks for review and merge

**Comment by pryorda** [comment]
More to Come!

**Pull request merged**
