### PR TITLE
Ensure 'section' arg in url is respected

### PR DESCRIPTION
**Pull request by Jc2k**
This is a python3 / twisted thing, url parameters are byte strings not unicode strings. So the `section` url param isn't working. This PR fixes it and adds a unit test for it.

### CODE REVIEW

**Comment by pryorda** [comment]
@Jc2k How do you feel about forcing signed commits? I like the idea, but i'm not sure if its to strict.

**Comment by pryorda** [comment]
Ah, so I have a little more security then that. I'll remove the requirement for now but we should def discuss more.

**Comment by Jc2k** [comment]
Yes let’s - sounds interesting

**Comment by pryorda** [comment]
#78 Created for this discussion

**Pull request merged**
